#############################################################################
# Makefile for building: LoveLetter
# Generated by qmake (2.01a) (Qt 4.8.7) on: dim. avr. 22 14:58:06 2018
# Project:  LoveLetter.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile LoveLetter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		main.cpp \
		joueur_view.cpp \
		Deck.cpp \
		Game.cpp \
		Hand.cpp \
		Player.cpp \
		Card.cpp \
		carte_view.cpp moc_mainwindow.cpp \
		moc_joueur_view.cpp \
		moc_carte_view.cpp
OBJECTS       = mainwindow.o \
		main.o \
		joueur_view.o \
		Deck.o \
		Game.o \
		Hand.o \
		Player.o \
		Card.o \
		carte_view.o \
		moc_mainwindow.o \
		moc_joueur_view.o \
		moc_carte_view.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		LoveLetter.pro
QMAKE_TARGET  = LoveLetter
DESTDIR       = 
TARGET        = LoveLetter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LoveLetter.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile LoveLetter.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile LoveLetter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LoveLetter1.0.0 || $(MKDIR) .tmp/LoveLetter1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LoveLetter1.0.0/ && $(COPY_FILE) --parents mainwindow.h ressources.h joueur_view.h carte_view.h Game.h Deck.h Hand.h Player.h Card.h .tmp/LoveLetter1.0.0/ && $(COPY_FILE) --parents mainwindow.cpp main.cpp joueur_view.cpp Deck.cpp Game.cpp Hand.cpp Player.cpp Card.cpp carte_view.cpp .tmp/LoveLetter1.0.0/ && (cd `dirname .tmp/LoveLetter1.0.0` && $(TAR) LoveLetter1.0.0.tar LoveLetter1.0.0 && $(COMPRESS) LoveLetter1.0.0.tar) && $(MOVE) `dirname .tmp/LoveLetter1.0.0`/LoveLetter1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LoveLetter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_joueur_view.cpp moc_carte_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_joueur_view.cpp moc_carte_view.cpp
moc_mainwindow.cpp: joueur_view.h \
		carte_view.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_joueur_view.cpp: carte_view.h \
		joueur_view.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) joueur_view.h -o moc_joueur_view.cpp

moc_carte_view.cpp: carte_view.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) carte_view.h -o moc_carte_view.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

mainwindow.o: mainwindow.cpp mainwindow.h \
		joueur_view.h \
		carte_view.h \
		Player.h \
		Deck.h \
		Hand.h \
		Card.h \
		Game.h \
		ressources.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

main.o: main.cpp mainwindow.h \
		joueur_view.h \
		carte_view.h \
		Game.h \
		Deck.h \
		Hand.h \
		Card.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

joueur_view.o: joueur_view.cpp joueur_view.h \
		carte_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o joueur_view.o joueur_view.cpp

Deck.o: Deck.cpp Deck.h \
		Hand.h \
		Card.h \
		carte_view.h \
		joueur_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Deck.o Deck.cpp

Game.o: Game.cpp Game.h \
		Deck.h \
		Hand.h \
		Card.h \
		carte_view.h \
		joueur_view.h \
		mainwindow.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

Hand.o: Hand.cpp Hand.h \
		Card.h \
		carte_view.h \
		joueur_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hand.o Hand.cpp

Player.o: Player.cpp Player.h \
		Deck.h \
		Hand.h \
		Card.h \
		carte_view.h \
		joueur_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

Card.o: Card.cpp Card.h \
		carte_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Card.o Card.cpp

carte_view.o: carte_view.cpp carte_view.h \
		Game.h \
		Deck.h \
		Hand.h \
		Card.h \
		joueur_view.h \
		mainwindow.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carte_view.o carte_view.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_joueur_view.o: moc_joueur_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_joueur_view.o moc_joueur_view.cpp

moc_carte_view.o: moc_carte_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_carte_view.o moc_carte_view.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

